// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function DiscoverAutoFilterPaths():Promise<Array<string>>;

export function GetAppInfo():Promise<main.AppInfo>;

export function LoadCSVPreview(arg1:Array<string>):Promise<main.CSVPreview>;

export function LoadTimeSelectorData(arg1:Array<string>):Promise<backend.TimeSelectorData>;

export function OpenContainingFolder(arg1:string):Promise<void>;

export function PickFilterFiles():Promise<Array<string>>;

export function PickInputCSVFile():Promise<string>;

export function PickInputCSVPaths():Promise<Array<string>>;

export function PickMobileLTECSVFile():Promise<string>;

export function RunProcessingWithConfig(arg1:backend.ProcessingConfig):Promise<backend.ProcessingResult>;
