// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function DiscoverAutoFilterPaths():Promise<Array<string>>;

export function LoadCSVPreview(arg1:string):Promise<main.CSVPreview>;

export function PickFilterFiles():Promise<Array<string>>;

export function PickInputCSVFile():Promise<string>;

export function PickMobileLTECSVFile():Promise<string>;

export function RunProcessingWithConfig(arg1:backend.ProcessingConfig):Promise<backend.ProcessingResult>;
