// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function DefaultOutputPaths(arg1:string,arg2:boolean,arg3:string):Promise<main.DefaultOutputPathsResult>;

export function DeletePreset(arg1:string):Promise<void>;

export function DiscoverAutoFilterPaths():Promise<Array<string>>;

export function GetAppInfo():Promise<main.AppInfo>;

export function LoadCSVPreview(arg1:Array<string>):Promise<main.CSVPreview>;

export function SavePreset(arg1:any):Promise<main.ProcessingPreset>;

export function LoadPreset(arg1:string):Promise<main.ProcessingPreset>;

export function ListPresets():Promise<Array<main.ProcessingPreset>>;

export function OpenContainingFolder(arg1:string):Promise<void>;

export function PickFilterFiles():Promise<Array<string>>;

export function PickInputCSVFile():Promise<string>;

export function PickInputCSVPaths():Promise<Array<string>>;

export function PickMobileLTECSVFile():Promise<string>;

export function PickMobileLTECSVPaths():Promise<Array<string>>;

export function PickOutputCSVFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunProcessingWithConfig(arg1:backend.ProcessingConfig):Promise<backend.ProcessingResult>;

export function StartLoadCSVPreview(arg1:number,arg2:Array<string>):Promise<void>;
