// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverAutoFilterPaths() {
  return window['go']['main']['App']['DiscoverAutoFilterPaths']();
}

export function LoadCSVPreview(arg1) {
  return window['go']['main']['App']['LoadCSVPreview'](arg1);
}

export function PickFilterFiles() {
  return window['go']['main']['App']['PickFilterFiles']();
}

export function PickInputCSVFile() {
  return window['go']['main']['App']['PickInputCSVFile']();
}

export function PickMobileLTECSVFile() {
  return window['go']['main']['App']['PickMobileLTECSVFile']();
}

export function RunProcessingWithConfig(arg1) {
  return window['go']['main']['App']['RunProcessingWithConfig'](arg1);
}
