// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultOutputPaths(arg1, arg2, arg3) {
  return window['go']['main']['App']['DefaultOutputPaths'](arg1, arg2, arg3);
}

export function DiscoverAutoFilterPaths() {
  return window['go']['main']['App']['DiscoverAutoFilterPaths']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function LoadCSVPreview(arg1) {
  return window['go']['main']['App']['LoadCSVPreview'](arg1);
}

export function OpenContainingFolder(arg1) {
  return window['go']['main']['App']['OpenContainingFolder'](arg1);
}

export function PickFilterFiles() {
  return window['go']['main']['App']['PickFilterFiles']();
}

export function PickInputCSVFile() {
  return window['go']['main']['App']['PickInputCSVFile']();
}

export function PickInputCSVPaths() {
  return window['go']['main']['App']['PickInputCSVPaths']();
}

export function PickMobileLTECSVFile() {
  return window['go']['main']['App']['PickMobileLTECSVFile']();
}

export function PickMobileLTECSVPaths() {
  return window['go']['main']['App']['PickMobileLTECSVPaths']();
}

export function PickOutputCSVFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PickOutputCSVFile'](arg1, arg2, arg3);
}

export function RunProcessingWithConfig(arg1) {
  return window['go']['main']['App']['RunProcessingWithConfig'](arg1);
}

export function StartLoadCSVPreview(arg1, arg2) {
  return window['go']['main']['App']['StartLoadCSVPreview'](arg1, arg2);
}
